### ISSUE TITLE
iterm companion theme

### ISSUE THREAD

**Issue by chalmagean** [tejr/sahara#2]
I'm just wondering, what theme are you using in iTerm2 with this one?

Thanks,
-- Cezar

**Comment by tejr** [comment]
Hi Cezar; I don't use iTerm2. :)

**Comment by chalmagean** [comment]
So can you post a screen shot of it? It would be interesting to see how this really looks cause using it in iTerm (or any other terminal) will probably alter it's color scheme.

**Comment by tejr** [comment]
Sure; done. Check the `README.markdown` and `screenshot.png` now.
